version: "3.8"

services:
  frontend:
    image: janithdev/kudos-craft-frontend:${BUILD_NUMBER}
    container_name: frontend-prod
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    environment:
      - BACKEND_URL=http://backend:3000/api/
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost:3000
      - NEXTAUTH_SECRET=janithchamikara
      - NEXTAUTH_URL=http://localhost:3000
      - FRONTEND_URL=http://localhost:3000
      - NEXT_PUBLIC_SUPABASE_URL=https://bjognysblrcgbynqjres.supabase.co
      - NEXT_PUBLIC_SUPABASE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqb2dueXNibHJjZ2J5bnFqcmVzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MDQwMzM5OCwiZXhwIjoyMDU1OTc5Mzk4fQ.9vSaItHcMPH_xmNNsay8dLJBo7DmfFZtsq3QPZoklh0
      - STRIPE_SECRET_KEY=sk_test_51QiYlJApCGLhfsDLMdaD0wRSnYxjv12IOPx5cXCR18nPgKcdVcOCR8P6FE6d29hywaxT2iT2dP7cnafBj6VC8x0900dQFzqNFs
      - STRIPE_WEBHOOK_SECRET=whsec_4033181472a28274872efcaa354b087cefb4b6496b68b8bb7cd5723713551bf5
      - NEXT_PUBLIC_STRIPE_PRICE_ID=price_1QiZbgApCGLhfsDLBuffQC1t
      - NEXT_PUBLIC_STRIPE_PUBLIC_KEY=pk_test_51QiYlJApCGLhfsDLDtA6RNUJuUY8buS1yDkrzK1qWzVuR95JAloPfxk5XhDXv4vg5cqRfBdcde5wxxOW8lclpcKu00sAk5hebq

  backend:
    image: janithdev/kudos-craft-backend:${BUILD_NUMBER}
    container_name: backend-prod
    ports:
      - "3001:3000"
      - "5555:5555"
    depends_on:
      - db
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
      - NODE_ENV=development
      - JWT_SECRET=janithchamikara
      - GEMINI_API_KEY=test
      - ACCESS_TOKEN_VALIDITY_DURATION_IN_SEC=300000
      - REFRESH_TOKEN_VALIDITY_DURATION_IN_SEC=300000
      - ACCESS_TOKEN_SECRET=janithchamikara
      - REFRESH_TOKEN_SECRET=janithchamikara
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=kudoscraft.contact@gmail.com
      - SMTP_PASSWORD=pzef jrzq hduo qfwr
      - SMTP_FROM_EMAIL=kudoscraft.contact@gmail.com

  db:
    image: postgres:17.6-alpine
    container_name: postgres-prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    restart: always

volumes:
  postgres_data:
