version: "3.8"

services:
  frontend:
    image: janithdev/kudos-craft-frontend:${BUILD_NUMBER}
    container_name: frontend-prod
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    environment:
      - BACKEND_URL=http://backend:3001/api/
      - NEXT_PUBLIC_FRONTEND_URL=${FRONTEND_DOMAIN}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${FRONTEND_DOMAIN}
      - FRONTEND_URL=${FRONTEND_DOMAIN}
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ROLE_KEY=${SUPABASE_ROLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - NEXT_PUBLIC_STRIPE_PRICE_ID=${STRIPE_PRICE_ID}
      - NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}

  backend:
    image: janithdev/kudos-craft-backend:${BUILD_NUMBER}
    container_name: backend-prod
    ports:
      - "3001:3000"
    depends_on:
      - db
    restart: always
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - NODE_ENV=production

  db:
    image: postgres:17.6-alpine
    container_name: postgres-prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always

volumes:
  postgres_data:
